version: '3'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: bookstore
    container_name: bookstore_spring_pg
    volumes:
      - ./postgres:/var/lib/postgresql/data